replicaCount: 1

image:
  repository: bank/blocker-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8088

resources: {}

env:
  SERVER_PORT: "8088"
  BLOCK_PROBABILITY: "0.3"
  ZIPKIN_ENDPOINT: "http://bank-zipkin:9411/api/v2/spans"
  LOGS_KAFKA_BOOTSTRAP_SERVERS: "{{ printf \"%s-kafka:9092\" .Release.Name }}"
  LOGS_TOPIC: "service-logs"
  LOGS_KAFKA_ENABLED: "true"
