version: '3.8'

services:
  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bank -d bank" ]
      interval: 5s
      timeout: 5s
      retries: 10
    image: postgres:16-alpine
    container_name: bank-postgres
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank123
      POSTGRES_DB: bank
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - bank-network

  keycloak:
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080/health/ready" ]
      interval: 5s
      timeout: 5s
      retries: 30
    image: quay.io/keycloak/keycloak:23.0
    container_name: bank-keycloak
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/bank
      KC_DB_USERNAME: bank
      KC_DB_PASSWORD: bank123
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_FRONTEND_URL: http://localhost:8080
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  postgres_data:
