replicaCount: 1

image:
  repository: bank/exchange-generator-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8087

resources: {}

env:
  SERVER_PORT: "8087"
  BASE_CURRENCY: RUB
  TARGET_CURRENCIES: USD,CNY
  GENERATION_PERIOD_MS: "3000"
  KAFKA_BOOTSTRAP_SERVERS: "{{ printf \"%s-kafka:9092\" .Release.Name }}"
  KAFKA_RATES_TOPIC: "fx-rates"
  ZIPKIN_ENDPOINT: "http://bank-zipkin:9411/api/v2/spans"
  LOGS_KAFKA_BOOTSTRAP_SERVERS: "{{ printf \"%s-kafka:9092\" .Release.Name }}"
  LOGS_TOPIC: "service-logs"
  LOGS_KAFKA_ENABLED: "true"
