image:
  repository: openzipkin/zipkin
  tag: "3.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9411

env:
  storageType: mem
  extra: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
