apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-front-ui
spec:
  ingressClassName: nginx
  rules:
    - host: bank.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bank-front-ui
                port:
                  number: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-keycloak
spec:
  ingressClassName: nginx
  rules:
    - host: keycloak.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bank-keycloak
                port:
                  number: 8080
