apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk.fullname" . }}-elasticsearch
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "elk.name" . }}-elasticsearch
    app.kubernetes.io/instance: {{ .Release.Name }}
