server:
  port: ${SERVER_PORT:8087}

spring:
  application:
    name: exchange-generator-service

app:
  exchange-base-url: ${EXCHANGE_BASE_URL:http://exchange-service:8086}
  exchange-generator:
    base-currency: ${BASE_CURRENCY:RUB}
    target-currencies: ${TARGET_CURRENCIES:USD,CNY}
    period-ms: ${GENERATION_PERIOD_MS:3000}
