server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: transfer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:bank-kafka:9092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${SPRING_DATASOURCE_USERNAME:bank}
    password: ${SPRING_DATASOURCE_PASSWORD:bank123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: transfer
    open-in-view: false
app:
  blocker-base-url: ${BLOCKER_BASE_URL:http://blocker-service:8088}
notifications:
  topic: ${KAFKA_NOTIFICATIONS_TOPIC:notifications}
  enabled: ${NOTIFICATIONS_ENABLED:true}
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
