apiVersion: v2
name: bank
description: Umbrella chart for bank microservices
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"

dependencies:
  - name: postgres
    version: 0.1.0
    repository: "file://../postgres"
  - name: keycloak
    version: 0.1.0
    repository: "file://../keycloak"
  - name: accounts-service
    version: 0.1.0
    repository: "file://../accounts-service"
  - name: notifications-service
    version: 0.1.0
    repository: "file://../notifications-service"
  - name: cash-service
    version: 0.1.0
    repository: "file://../cash-service"
  - name: transfer-service
    version: 0.1.0
    repository: "file://../transfer-service"
  - name: blocker-service
    version: 0.1.0
    repository: "file://../blocker-service"
  - name: exchange-service
    version: 0.1.0
    repository: "file://../exchange-service"
  - name: exchange-generator-service
    version: 0.1.0
    repository: "file://../exchange-generator-service"
  - name: front-ui
    version: 0.1.0
    repository: "file://../front-ui"
  - name: kafka
    version: 26.6.1
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
