front-ui:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: bank.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: Prefix
  env:
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak.127.0.0.1.nip.io/realms/bank
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTH_URI: http://keycloak.127.0.0.1.nip.io/realms/bank/protocol/openid-connect/auth
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: http://bank-keycloak:8080/realms/bank/protocol/openid-connect/token
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI: http://bank-keycloak:8080/realms/bank/protocol/openid-connect/certs
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_END_SESSION_URI: http://keycloak.127.0.0.1.nip.io/realms/bank/protocol/openid-connect/logout

keycloak:
  image:
    repository: bank/keycloak
    tag: "23.0-custom"
  env:
    KC_HOSTNAME: keycloak.127.0.0.1.nip.io
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: keycloak.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: Prefix

kafka:
  image:
    tag: "4.0.0-debian-12-r0"
  controller:
    replicaCount: 1
    persistence:
      size: 2Gi
  broker:
    replicaCount: 0
    persistence:
      size: 2Gi
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
  auth:
    clientProtocol: plaintext
    interBrokerProtocol: plaintext
    controllerProtocol: plaintext
  persistence:
    enabled: true
    size: 2Gi
  zookeeper:
    replicaCount: 1
    persistence:
      enabled: true
      size: 2Gi
  configurationOverrides:
    auto.create.topics.enable: "true"
