replicaCount: 1

image:
  repository: bank/front-ui
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  className: ""
  hosts:
    - host: bank.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

env:
  SERVER_PORT: "8081"
  ACCOUNTS_BASE_URL: "{{ printf \"http://%s-accounts-service:8082\" .Release.Name }}"
  CASH_BASE_URL: "{{ printf \"http://%s-cash-service:8083\" .Release.Name }}"
  TRANSFER_BASE_URL: "{{ printf \"http://%s-transfer-service:8085\" .Release.Name }}"
  EXCHANGE_BASE_URL: "{{ printf \"http://%s-exchange-service:8086\" .Release.Name }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: "{{ printf \"http://%s-keycloak:8080/realms/bank\" .Release.Name }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTH_URI: "{{ printf \"http://%s-keycloak:8080/realms/bank/protocol/openid-connect/auth\" .Release.Name }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: "{{ printf \"http://%s-keycloak:8080/realms/bank/protocol/openid-connect/token\" .Release.Name }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI: "{{ printf \"http://%s-keycloak:8080/realms/bank/protocol/openid-connect/certs\" .Release.Name }}"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_END_SESSION_URI: "http://keycloak.127.0.0.1.nip.io/realms/bank/protocol/openid-connect/logout"
  ZIPKIN_ENDPOINT: "http://bank-zipkin:9411/api/v2/spans"
  LOGS_KAFKA_BOOTSTRAP_SERVERS: "{{ printf \"%s-kafka:9092\" .Release.Name }}"
  LOGS_TOPIC: "service-logs"
  LOGS_KAFKA_ENABLED: "true"
