server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: accounts-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:bank-kafka:9092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${SPRING_DATASOURCE_USERNAME:bank}
    password: ${SPRING_DATASOURCE_PASSWORD:bank123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: accounts
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak:8080/realms/bank/protocol/openid-connect/certs}
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/bank}
keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:bank}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin123}

notifications:
  base-url: ${NOTIFICATIONS_BASE_URL:http://notifications-service:8084}
  enabled: ${NOTIFICATIONS_ENABLED:true}
  # Kafka topic for notifications
  topic: ${KAFKA_NOTIFICATIONS_TOPIC:notifications}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
