apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-config" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ tpl $value $ }}"
{{- end }}
